steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
  - -c
  - |
    ls -la
    # gcloud compute instances create inspec-master \
    # --image inspec-image \
    # --zone us-west1-b \
    # --metadata-from-file startup-script=workspace/startup.sh


    # 削除コマンド ※確認のyを押さないと消せないの？
    #gcloud compute instances delete inspec-master-vol2 --zone=us-west1-b