steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
  - -c
  - |
    gcloud secrets versions access --secret=ssh-key latest > /root/.ssh/id_rsa
  volumes:
  - name: ssh
    path: /root/.ssh

# 秘密鍵を置くディレクトリ、鍵のパーミッション変更、configファイルを作成
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args:
    - -c
    - |
      chmod 600 /root/.ssh/id_rsa
      chmod 700 /root/.ssh
      cat <<EOF >/root/.ssh/config
      User kodhikodhi
      IdentityFile /root/.ssh/id_rsa
      StrictHostKeyChecking no
      EOF
  volumes:
  - name: ssh
    path: /root/.ssh

# - name: gcr.io/cloud-builders/gcloud
#   entrypoint: bash
#   args:
#   - -c
#   - |
#     ls -la
#     gcloud compute instances create inspec-master \
#     --image inspec-image \
#     --zone us-west1-b \
#     # --metadata-from-file startup-script=startup.sh
#     --metadata-from-file pubkey=id_rsa.pub


#     # 削除コマンド ※確認のyを押さないと消せないの？
#     # gcloud compute instances delete inspec-master-vol2 --zone=us-west1-b

#     # テストされる側のインスタンス
#     # gcloud compute instances create test-server4 \
#     # --zone us-west1-b \
#     # --image-family=centos-7 --image-project=centos-cloud \
#     # --machine-type f1-micro \
#     # --network-interface no-address

- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      # gcloud compute instances list --filter="name='inspec-master'" --format="value(networkInterfaces[].accessConfigs[0].natIP)" > _IPADD
      ssh -i /root/.ssh/id_rsa kodhikodhi@35.247.116.152
  volumes:
  - name: ssh
    path: /root/.ssh  